### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bfarzin** [hartikainen/easy21#1]
https://github.com/hartikainen/easy21/blob/41677ff32cd18db7601a633c7f98d5f7cd6e149d/environment.py#L92

Thanks for your write-up on this! I missed the `0<` condition and was struggling to get sensible graphs.  

Nothing to resolve here, you got it right.  Just saying thank you!

**Comment by hartikainen** [comment]
I'm really glad that it's been helpful!
